### ISSUE TITLE
The plugin won't close Streams

### ISSUE THREAD

**Issue by sebasblancogonz** [emundo/7z-gradle-plugin#4]
Since it won't close Streams, it'll make impossible to delete the .7z file and it's parent folder.

**Comment by simonnagl** [comment]
Hi @sebasblancogonz, thank you for reporting thins bug. You are totally right. We will fix this issue in our next release.

**Comment by sebasblancogonz** [comment]
Great! I could submit a PR if you like

**Comment by simonnagl** [comment]
Contributions are welcome!

**Comment by simonnagl** [comment]
I just published Version 1.0.5 of the plugin. I hope it fixes your issues. If not, please reopen this bug.
